allowBuilds:
  esbuild: true
  sharp: true
  unrs-resolver: true
  workerd: true

onlyBuiltDependencies:
  - sharp
  - esbuild
  - unrs-resolver

overrides:
  '@esbuild-kit/core-utils>esbuild': 0.25.12
  dompurify: 3.4.13
